/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ClassificaRouteImport } from './routes/classifica'
import { Route as MixedZoneRouteImport } from './routes/mixed-zone'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAmichevoliRouteImport } from './routes/admin.amichevoli'
import { Route as AdminClassificheRouteImport } from './routes/admin.classifiche'
import { Route as AdminDocumentiRouteImport } from './routes/admin.documenti'
import { Route as AdminGiocatoriRouteImport } from './routes/admin.giocatori'
import { Route as AdminGraficheRouteImport } from './routes/admin.grafiche'
import { Route as AdminImpostazioniRouteImport } from './routes/admin.impostazioni'
import { Route as AdminPagamentiRouteImport } from './routes/admin.pagamenti'
import { Route as AdminSincronizzazioneRouteImport } from './routes/admin.sincronizzazione'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as MixedZoneIndexRouteImport } from './routes/mixed-zone.index'
import { Route as MixedZoneStatisticheRouteImport } from './routes/mixed-zone.statistiche'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as PartiteMatchIdRouteImport } from './routes/partite.$matchId'
import { Route as RosaIndexRouteImport } from './routes/rosa.index'
import { Route as RosaPlayerIdRouteImport } from './routes/rosa.$playerId'
import { Route as StoricoIndexRouteImport } from './routes/storico.index'
import { Route as StoricoCompetitionIdRouteImport } from './routes/storico.$competitionId'
import { Route as AdminPartiteIndexRouteImport } from './routes/admin.partite.index'
import { Route as AdminPartiteMatchIdRouteImport } from './routes/admin.partite.$matchId'
import { Route as MixedZoneGiocatoriIndexRouteImport } from './routes/mixed-zone.giocatori.index'
import { Route as MixedZoneGiocatoriIdRouteImport } from './routes/mixed-zone.giocatori.$id'
import { Route as MixedZonePartiteIndexRouteImport } from './routes/mixed-zone.partite.index'
import { Route as MixedZonePartiteIdRouteImport } from './routes/mixed-zone.partite.$id'
import { Route as MixedZoneSquadreIndexRouteImport } from './routes/mixed-zone.squadre.index'
import { Route as MixedZoneSquadreIdRouteImport } from './routes/mixed-zone.squadre.$id'
import { Route as MixedZoneTorneiIndexRouteImport } from './routes/mixed-zone.tornei.index'
import { Route as MixedZoneTorneiIdRouteImport } from './routes/mixed-zone.tornei.$id'
import { Route as StoricoStagioneSeasonRouteImport } from './routes/storico.stagione.$season'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificaRoute = ClassificaRouteImport.update({
  id: '/classifica',
  path: '/classifica',
  getParentRoute: () => rootRouteImport,
} as any)
const MixedZoneRoute = MixedZoneRouteImport.update({
  id: '/mixed-zone',
  path: '/mixed-zone',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAmichevoliRoute = AdminAmichevoliRouteImport.update({
  id: '/amichevoli',
  path: '/amichevoli',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassificheRoute = AdminClassificheRouteImport.update({
  id: '/classifiche',
  path: '/classifiche',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentiRoute = AdminDocumentiRouteImport.update({
  id: '/documenti',
  path: '/documenti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGiocatoriRoute = AdminGiocatoriRouteImport.update({
  id: '/giocatori',
  path: '/giocatori',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGraficheRoute = AdminGraficheRouteImport.update({
  id: '/grafiche',
  path: '/grafiche',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpostazioniRoute = AdminImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagamentiRoute = AdminPagamentiRouteImport.update({
  id: '/pagamenti',
  path: '/pagamenti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSincronizzazioneRoute = AdminSincronizzazioneRouteImport.update({
  id: '/sincronizzazione',
  path: '/sincronizzazione',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MixedZoneIndexRoute = MixedZoneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneStatisticheRoute = MixedZoneStatisticheRouteImport.update({
  id: '/statistiche',
  path: '/statistiche',
  getParentRoute: () => MixedZoneRoute,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PartiteMatchIdRoute = PartiteMatchIdRouteImport.update({
  id: '/partite/$matchId',
  path: '/partite/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RosaIndexRoute = RosaIndexRouteImport.update({
  id: '/rosa/',
  path: '/rosa/',
  getParentRoute: () => rootRouteImport,
} as any)
const RosaPlayerIdRoute = RosaPlayerIdRouteImport.update({
  id: '/rosa/$playerId',
  path: '/rosa/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoricoIndexRoute = StoricoIndexRouteImport.update({
  id: '/storico/',
  path: '/storico/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoricoCompetitionIdRoute = StoricoCompetitionIdRouteImport.update({
  id: '/storico/$competitionId',
  path: '/storico/$competitionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartiteIndexRoute = AdminPartiteIndexRouteImport.update({
  id: '/partite/',
  path: '/partite/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartiteMatchIdRoute = AdminPartiteMatchIdRouteImport.update({
  id: '/partite/$matchId',
  path: '/partite/$matchId',
  getParentRoute: () => AdminRoute,
} as any)
const MixedZoneGiocatoriIndexRoute = MixedZoneGiocatoriIndexRouteImport.update({
  id: '/giocatori/',
  path: '/giocatori/',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneGiocatoriIdRoute = MixedZoneGiocatoriIdRouteImport.update({
  id: '/giocatori/$id',
  path: '/giocatori/$id',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZonePartiteIndexRoute = MixedZonePartiteIndexRouteImport.update({
  id: '/partite/',
  path: '/partite/',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZonePartiteIdRoute = MixedZonePartiteIdRouteImport.update({
  id: '/partite/$id',
  path: '/partite/$id',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneSquadreIndexRoute = MixedZoneSquadreIndexRouteImport.update({
  id: '/squadre/',
  path: '/squadre/',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneSquadreIdRoute = MixedZoneSquadreIdRouteImport.update({
  id: '/squadre/$id',
  path: '/squadre/$id',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneTorneiIndexRoute = MixedZoneTorneiIndexRouteImport.update({
  id: '/tornei/',
  path: '/tornei/',
  getParentRoute: () => MixedZoneRoute,
} as any)
const MixedZoneTorneiIdRoute = MixedZoneTorneiIdRouteImport.update({
  id: '/tornei/$id',
  path: '/tornei/$id',
  getParentRoute: () => MixedZoneRoute,
} as any)
const StoricoStagioneSeasonRoute = StoricoStagioneSeasonRouteImport.update({
  id: '/storico/stagione/$season',
  path: '/storico/stagione/$season',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/classifica': typeof ClassificaRoute
  '/mixed-zone': typeof MixedZoneRouteWithChildren
  '/admin/amichevoli': typeof AdminAmichevoliRoute
  '/admin/classifiche': typeof AdminClassificheRoute
  '/admin/documenti': typeof AdminDocumentiRoute
  '/admin/giocatori': typeof AdminGiocatoriRoute
  '/admin/grafiche': typeof AdminGraficheRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/pagamenti': typeof AdminPagamentiRoute
  '/admin/sincronizzazione': typeof AdminSincronizzazioneRoute
  '/admin/login': typeof AdminLoginRoute
  '/mixed-zone/statistiche': typeof MixedZoneStatisticheRoute
  '/p/$token': typeof PTokenRoute
  '/partite/$matchId': typeof PartiteMatchIdRoute
  '/rosa/$playerId': typeof RosaPlayerIdRoute
  '/storico/$competitionId': typeof StoricoCompetitionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/mixed-zone/': typeof MixedZoneIndexRoute
  '/rosa/': typeof RosaIndexRoute
  '/storico/': typeof StoricoIndexRoute
  '/admin/partite/$matchId': typeof AdminPartiteMatchIdRoute
  '/mixed-zone/giocatori/$id': typeof MixedZoneGiocatoriIdRoute
  '/mixed-zone/partite/$id': typeof MixedZonePartiteIdRoute
  '/mixed-zone/squadre/$id': typeof MixedZoneSquadreIdRoute
  '/mixed-zone/tornei/$id': typeof MixedZoneTorneiIdRoute
  '/storico/stagione/$season': typeof StoricoStagioneSeasonRoute
  '/admin/partite/': typeof AdminPartiteIndexRoute
  '/mixed-zone/giocatori/': typeof MixedZoneGiocatoriIndexRoute
  '/mixed-zone/partite/': typeof MixedZonePartiteIndexRoute
  '/mixed-zone/squadre/': typeof MixedZoneSquadreIndexRoute
  '/mixed-zone/tornei/': typeof MixedZoneTorneiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/classifica': typeof ClassificaRoute
  '/admin/amichevoli': typeof AdminAmichevoliRoute
  '/admin/classifiche': typeof AdminClassificheRoute
  '/admin/documenti': typeof AdminDocumentiRoute
  '/admin/giocatori': typeof AdminGiocatoriRoute
  '/admin/grafiche': typeof AdminGraficheRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/pagamenti': typeof AdminPagamentiRoute
  '/admin/sincronizzazione': typeof AdminSincronizzazioneRoute
  '/admin/login': typeof AdminLoginRoute
  '/mixed-zone/statistiche': typeof MixedZoneStatisticheRoute
  '/p/$token': typeof PTokenRoute
  '/partite/$matchId': typeof PartiteMatchIdRoute
  '/rosa/$playerId': typeof RosaPlayerIdRoute
  '/storico/$competitionId': typeof StoricoCompetitionIdRoute
  '/admin': typeof AdminIndexRoute
  '/mixed-zone': typeof MixedZoneIndexRoute
  '/rosa': typeof RosaIndexRoute
  '/storico': typeof StoricoIndexRoute
  '/admin/partite/$matchId': typeof AdminPartiteMatchIdRoute
  '/mixed-zone/giocatori/$id': typeof MixedZoneGiocatoriIdRoute
  '/mixed-zone/partite/$id': typeof MixedZonePartiteIdRoute
  '/mixed-zone/squadre/$id': typeof MixedZoneSquadreIdRoute
  '/mixed-zone/tornei/$id': typeof MixedZoneTorneiIdRoute
  '/storico/stagione/$season': typeof StoricoStagioneSeasonRoute
  '/admin/partite': typeof AdminPartiteIndexRoute
  '/mixed-zone/giocatori': typeof MixedZoneGiocatoriIndexRoute
  '/mixed-zone/partite': typeof MixedZonePartiteIndexRoute
  '/mixed-zone/squadre': typeof MixedZoneSquadreIndexRoute
  '/mixed-zone/tornei': typeof MixedZoneTorneiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/classifica': typeof ClassificaRoute
  '/mixed-zone': typeof MixedZoneRouteWithChildren
  '/admin/amichevoli': typeof AdminAmichevoliRoute
  '/admin/classifiche': typeof AdminClassificheRoute
  '/admin/documenti': typeof AdminDocumentiRoute
  '/admin/giocatori': typeof AdminGiocatoriRoute
  '/admin/grafiche': typeof AdminGraficheRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/pagamenti': typeof AdminPagamentiRoute
  '/admin/sincronizzazione': typeof AdminSincronizzazioneRoute
  '/admin_/login': typeof AdminLoginRoute
  '/mixed-zone/statistiche': typeof MixedZoneStatisticheRoute
  '/p/$token': typeof PTokenRoute
  '/partite/$matchId': typeof PartiteMatchIdRoute
  '/rosa/$playerId': typeof RosaPlayerIdRoute
  '/storico/$competitionId': typeof StoricoCompetitionIdRoute
  '/admin/': typeof AdminIndexRoute
  '/mixed-zone/': typeof MixedZoneIndexRoute
  '/rosa/': typeof RosaIndexRoute
  '/storico/': typeof StoricoIndexRoute
  '/admin/partite/$matchId': typeof AdminPartiteMatchIdRoute
  '/mixed-zone/giocatori/$id': typeof MixedZoneGiocatoriIdRoute
  '/mixed-zone/partite/$id': typeof MixedZonePartiteIdRoute
  '/mixed-zone/squadre/$id': typeof MixedZoneSquadreIdRoute
  '/mixed-zone/tornei/$id': typeof MixedZoneTorneiIdRoute
  '/storico/stagione/$season': typeof StoricoStagioneSeasonRoute
  '/admin/partite/': typeof AdminPartiteIndexRoute
  '/mixed-zone/giocatori/': typeof MixedZoneGiocatoriIndexRoute
  '/mixed-zone/partite/': typeof MixedZonePartiteIndexRoute
  '/mixed-zone/squadre/': typeof MixedZoneSquadreIndexRoute
  '/mixed-zone/tornei/': typeof MixedZoneTorneiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendario'
    | '/classifica'
    | '/mixed-zone'
    | '/admin/amichevoli'
    | '/admin/classifiche'
    | '/admin/documenti'
    | '/admin/giocatori'
    | '/admin/grafiche'
    | '/admin/impostazioni'
    | '/admin/pagamenti'
    | '/admin/sincronizzazione'
    | '/admin/login'
    | '/mixed-zone/statistiche'
    | '/p/$token'
    | '/partite/$matchId'
    | '/rosa/$playerId'
    | '/storico/$competitionId'
    | '/admin/'
    | '/mixed-zone/'
    | '/rosa/'
    | '/storico/'
    | '/admin/partite/$matchId'
    | '/mixed-zone/giocatori/$id'
    | '/mixed-zone/partite/$id'
    | '/mixed-zone/squadre/$id'
    | '/mixed-zone/tornei/$id'
    | '/storico/stagione/$season'
    | '/admin/partite/'
    | '/mixed-zone/giocatori/'
    | '/mixed-zone/partite/'
    | '/mixed-zone/squadre/'
    | '/mixed-zone/tornei/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/classifica'
    | '/admin/amichevoli'
    | '/admin/classifiche'
    | '/admin/documenti'
    | '/admin/giocatori'
    | '/admin/grafiche'
    | '/admin/impostazioni'
    | '/admin/pagamenti'
    | '/admin/sincronizzazione'
    | '/admin/login'
    | '/mixed-zone/statistiche'
    | '/p/$token'
    | '/partite/$matchId'
    | '/rosa/$playerId'
    | '/storico/$competitionId'
    | '/admin'
    | '/mixed-zone'
    | '/rosa'
    | '/storico'
    | '/admin/partite/$matchId'
    | '/mixed-zone/giocatori/$id'
    | '/mixed-zone/partite/$id'
    | '/mixed-zone/squadre/$id'
    | '/mixed-zone/tornei/$id'
    | '/storico/stagione/$season'
    | '/admin/partite'
    | '/mixed-zone/giocatori'
    | '/mixed-zone/partite'
    | '/mixed-zone/squadre'
    | '/mixed-zone/tornei'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendario'
    | '/classifica'
    | '/mixed-zone'
    | '/admin/amichevoli'
    | '/admin/classifiche'
    | '/admin/documenti'
    | '/admin/giocatori'
    | '/admin/grafiche'
    | '/admin/impostazioni'
    | '/admin/pagamenti'
    | '/admin/sincronizzazione'
    | '/admin_/login'
    | '/mixed-zone/statistiche'
    | '/p/$token'
    | '/partite/$matchId'
    | '/rosa/$playerId'
    | '/storico/$competitionId'
    | '/admin/'
    | '/mixed-zone/'
    | '/rosa/'
    | '/storico/'
    | '/admin/partite/$matchId'
    | '/mixed-zone/giocatori/$id'
    | '/mixed-zone/partite/$id'
    | '/mixed-zone/squadre/$id'
    | '/mixed-zone/tornei/$id'
    | '/storico/stagione/$season'
    | '/admin/partite/'
    | '/mixed-zone/giocatori/'
    | '/mixed-zone/partite/'
    | '/mixed-zone/squadre/'
    | '/mixed-zone/tornei/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  ClassificaRoute: typeof ClassificaRoute
  MixedZoneRoute: typeof MixedZoneRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  PTokenRoute: typeof PTokenRoute
  PartiteMatchIdRoute: typeof PartiteMatchIdRoute
  RosaPlayerIdRoute: typeof RosaPlayerIdRoute
  StoricoCompetitionIdRoute: typeof StoricoCompetitionIdRoute
  RosaIndexRoute: typeof RosaIndexRoute
  StoricoIndexRoute: typeof StoricoIndexRoute
  StoricoStagioneSeasonRoute: typeof StoricoStagioneSeasonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifica': {
      id: '/classifica'
      path: '/classifica'
      fullPath: '/classifica'
      preLoaderRoute: typeof ClassificaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixed-zone': {
      id: '/mixed-zone'
      path: '/mixed-zone'
      fullPath: '/mixed-zone'
      preLoaderRoute: typeof MixedZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/amichevoli': {
      id: '/admin/amichevoli'
      path: '/amichevoli'
      fullPath: '/admin/amichevoli'
      preLoaderRoute: typeof AdminAmichevoliRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classifiche': {
      id: '/admin/classifiche'
      path: '/classifiche'
      fullPath: '/admin/classifiche'
      preLoaderRoute: typeof AdminClassificheRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documenti': {
      id: '/admin/documenti'
      path: '/documenti'
      fullPath: '/admin/documenti'
      preLoaderRoute: typeof AdminDocumentiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/giocatori': {
      id: '/admin/giocatori'
      path: '/giocatori'
      fullPath: '/admin/giocatori'
      preLoaderRoute: typeof AdminGiocatoriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/grafiche': {
      id: '/admin/grafiche'
      path: '/grafiche'
      fullPath: '/admin/grafiche'
      preLoaderRoute: typeof AdminGraficheRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impostazioni': {
      id: '/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AdminImpostazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pagamenti': {
      id: '/admin/pagamenti'
      path: '/pagamenti'
      fullPath: '/admin/pagamenti'
      preLoaderRoute: typeof AdminPagamentiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sincronizzazione': {
      id: '/admin/sincronizzazione'
      path: '/sincronizzazione'
      fullPath: '/admin/sincronizzazione'
      preLoaderRoute: typeof AdminSincronizzazioneRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixed-zone/': {
      id: '/mixed-zone/'
      path: '/'
      fullPath: '/mixed-zone/'
      preLoaderRoute: typeof MixedZoneIndexRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/statistiche': {
      id: '/mixed-zone/statistiche'
      path: '/statistiche'
      fullPath: '/mixed-zone/statistiche'
      preLoaderRoute: typeof MixedZoneStatisticheRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partite/$matchId': {
      id: '/partite/$matchId'
      path: '/partite/$matchId'
      fullPath: '/partite/$matchId'
      preLoaderRoute: typeof PartiteMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosa/': {
      id: '/rosa/'
      path: '/rosa'
      fullPath: '/rosa/'
      preLoaderRoute: typeof RosaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rosa/$playerId': {
      id: '/rosa/$playerId'
      path: '/rosa/$playerId'
      fullPath: '/rosa/$playerId'
      preLoaderRoute: typeof RosaPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storico/': {
      id: '/storico/'
      path: '/storico'
      fullPath: '/storico/'
      preLoaderRoute: typeof StoricoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storico/$competitionId': {
      id: '/storico/$competitionId'
      path: '/storico/$competitionId'
      fullPath: '/storico/$competitionId'
      preLoaderRoute: typeof StoricoCompetitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partite/': {
      id: '/admin/partite/'
      path: '/partite'
      fullPath: '/admin/partite/'
      preLoaderRoute: typeof AdminPartiteIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partite/$matchId': {
      id: '/admin/partite/$matchId'
      path: '/partite/$matchId'
      fullPath: '/admin/partite/$matchId'
      preLoaderRoute: typeof AdminPartiteMatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/mixed-zone/giocatori/': {
      id: '/mixed-zone/giocatori/'
      path: '/giocatori'
      fullPath: '/mixed-zone/giocatori/'
      preLoaderRoute: typeof MixedZoneGiocatoriIndexRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/giocatori/$id': {
      id: '/mixed-zone/giocatori/$id'
      path: '/giocatori/$id'
      fullPath: '/mixed-zone/giocatori/$id'
      preLoaderRoute: typeof MixedZoneGiocatoriIdRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/partite/': {
      id: '/mixed-zone/partite/'
      path: '/partite'
      fullPath: '/mixed-zone/partite/'
      preLoaderRoute: typeof MixedZonePartiteIndexRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/partite/$id': {
      id: '/mixed-zone/partite/$id'
      path: '/partite/$id'
      fullPath: '/mixed-zone/partite/$id'
      preLoaderRoute: typeof MixedZonePartiteIdRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/squadre/': {
      id: '/mixed-zone/squadre/'
      path: '/squadre'
      fullPath: '/mixed-zone/squadre/'
      preLoaderRoute: typeof MixedZoneSquadreIndexRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/squadre/$id': {
      id: '/mixed-zone/squadre/$id'
      path: '/squadre/$id'
      fullPath: '/mixed-zone/squadre/$id'
      preLoaderRoute: typeof MixedZoneSquadreIdRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/tornei/': {
      id: '/mixed-zone/tornei/'
      path: '/tornei'
      fullPath: '/mixed-zone/tornei/'
      preLoaderRoute: typeof MixedZoneTorneiIndexRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/mixed-zone/tornei/$id': {
      id: '/mixed-zone/tornei/$id'
      path: '/tornei/$id'
      fullPath: '/mixed-zone/tornei/$id'
      preLoaderRoute: typeof MixedZoneTorneiIdRouteImport
      parentRoute: typeof MixedZoneRoute
    }
    '/storico/stagione/$season': {
      id: '/storico/stagione/$season'
      path: '/storico/stagione/$season'
      fullPath: '/storico/stagione/$season'
      preLoaderRoute: typeof StoricoStagioneSeasonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAmichevoliRoute: typeof AdminAmichevoliRoute
  AdminClassificheRoute: typeof AdminClassificheRoute
  AdminDocumentiRoute: typeof AdminDocumentiRoute
  AdminGiocatoriRoute: typeof AdminGiocatoriRoute
  AdminGraficheRoute: typeof AdminGraficheRoute
  AdminImpostazioniRoute: typeof AdminImpostazioniRoute
  AdminPagamentiRoute: typeof AdminPagamentiRoute
  AdminSincronizzazioneRoute: typeof AdminSincronizzazioneRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPartiteMatchIdRoute: typeof AdminPartiteMatchIdRoute
  AdminPartiteIndexRoute: typeof AdminPartiteIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAmichevoliRoute: AdminAmichevoliRoute,
  AdminClassificheRoute: AdminClassificheRoute,
  AdminDocumentiRoute: AdminDocumentiRoute,
  AdminGiocatoriRoute: AdminGiocatoriRoute,
  AdminGraficheRoute: AdminGraficheRoute,
  AdminImpostazioniRoute: AdminImpostazioniRoute,
  AdminPagamentiRoute: AdminPagamentiRoute,
  AdminSincronizzazioneRoute: AdminSincronizzazioneRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPartiteMatchIdRoute: AdminPartiteMatchIdRoute,
  AdminPartiteIndexRoute: AdminPartiteIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MixedZoneRouteChildren {
  MixedZoneStatisticheRoute: typeof MixedZoneStatisticheRoute
  MixedZoneIndexRoute: typeof MixedZoneIndexRoute
  MixedZoneGiocatoriIdRoute: typeof MixedZoneGiocatoriIdRoute
  MixedZonePartiteIdRoute: typeof MixedZonePartiteIdRoute
  MixedZoneSquadreIdRoute: typeof MixedZoneSquadreIdRoute
  MixedZoneTorneiIdRoute: typeof MixedZoneTorneiIdRoute
  MixedZoneGiocatoriIndexRoute: typeof MixedZoneGiocatoriIndexRoute
  MixedZonePartiteIndexRoute: typeof MixedZonePartiteIndexRoute
  MixedZoneSquadreIndexRoute: typeof MixedZoneSquadreIndexRoute
  MixedZoneTorneiIndexRoute: typeof MixedZoneTorneiIndexRoute
}

const MixedZoneRouteChildren: MixedZoneRouteChildren = {
  MixedZoneStatisticheRoute: MixedZoneStatisticheRoute,
  MixedZoneIndexRoute: MixedZoneIndexRoute,
  MixedZoneGiocatoriIdRoute: MixedZoneGiocatoriIdRoute,
  MixedZonePartiteIdRoute: MixedZonePartiteIdRoute,
  MixedZoneSquadreIdRoute: MixedZoneSquadreIdRoute,
  MixedZoneTorneiIdRoute: MixedZoneTorneiIdRoute,
  MixedZoneGiocatoriIndexRoute: MixedZoneGiocatoriIndexRoute,
  MixedZonePartiteIndexRoute: MixedZonePartiteIndexRoute,
  MixedZoneSquadreIndexRoute: MixedZoneSquadreIndexRoute,
  MixedZoneTorneiIndexRoute: MixedZoneTorneiIndexRoute,
}

const MixedZoneRouteWithChildren = MixedZoneRoute._addFileChildren(
  MixedZoneRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  ClassificaRoute: ClassificaRoute,
  MixedZoneRoute: MixedZoneRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  PTokenRoute: PTokenRoute,
  PartiteMatchIdRoute: PartiteMatchIdRoute,
  RosaPlayerIdRoute: RosaPlayerIdRoute,
  StoricoCompetitionIdRoute: StoricoCompetitionIdRoute,
  RosaIndexRoute: RosaIndexRoute,
  StoricoIndexRoute: StoricoIndexRoute,
  StoricoStagioneSeasonRoute: StoricoStagioneSeasonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
